---
title: RNA-seq Graph
subtitle: Gene-structure prediction based on transcript sequences.
description: RNA-seq Graph is a tool  for gene-structure prediction based on transcript sequences without a reference genome.

url: http://algolab.github.com/RNA-seq-Graph
root: /RNA-seq-Graph 
author: AlgoLab

github_repository: RNA-seq-Graph
github_user: AlgoLab
github_tags_count: 3

nav:
  - name: Home
    link: "index.html"
  - name: Installation
    link: "install.html"
  - name: Usage
    link: "usage.html"
  - name: Issues
    link: "https://github.com/AlgoLab/RNA-seq-Graph/issues"

simple_search: http://google.com/search
google_analytics_tracking_id: UA-32216930-1
---
